// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shared.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PLAYER_ACTION int32

const (
	PLAYER_ACTION_PLAYER_ACTION_NONE               PLAYER_ACTION = 0
	PLAYER_ACTION_PLAYER_ACTION_LOOK               PLAYER_ACTION = 1
	PLAYER_ACTION_PLAYER_ACTION_USE                PLAYER_ACTION = 2
	PLAYER_ACTION_PLAYER_ACTION_OPEN               PLAYER_ACTION = 3
	PLAYER_ACTION_PLAYER_ACTION_AUTOWALK_HIGHLIGHT PLAYER_ACTION = 4
)

// Enum value maps for PLAYER_ACTION.
var (
	PLAYER_ACTION_name = map[int32]string{
		0: "PLAYER_ACTION_NONE",
		1: "PLAYER_ACTION_LOOK",
		2: "PLAYER_ACTION_USE",
		3: "PLAYER_ACTION_OPEN",
		4: "PLAYER_ACTION_AUTOWALK_HIGHLIGHT",
	}
	PLAYER_ACTION_value = map[string]int32{
		"PLAYER_ACTION_NONE":               0,
		"PLAYER_ACTION_LOOK":               1,
		"PLAYER_ACTION_USE":                2,
		"PLAYER_ACTION_OPEN":               3,
		"PLAYER_ACTION_AUTOWALK_HIGHLIGHT": 4,
	}
)

func (x PLAYER_ACTION) Enum() *PLAYER_ACTION {
	p := new(PLAYER_ACTION)
	*p = x
	return p
}

func (x PLAYER_ACTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLAYER_ACTION) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[0].Descriptor()
}

func (PLAYER_ACTION) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[0]
}

func (x PLAYER_ACTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PLAYER_ACTION) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PLAYER_ACTION(num)
	return nil
}

// Deprecated: Use PLAYER_ACTION.Descriptor instead.
func (PLAYER_ACTION) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{0}
}

type ITEM_CATEGORY int32

const (
	ITEM_CATEGORY_ITEM_CATEGORY_ARMORS            ITEM_CATEGORY = 1
	ITEM_CATEGORY_ITEM_CATEGORY_AMULETS           ITEM_CATEGORY = 2
	ITEM_CATEGORY_ITEM_CATEGORY_BOOTS             ITEM_CATEGORY = 3
	ITEM_CATEGORY_ITEM_CATEGORY_CONTAINERS        ITEM_CATEGORY = 4
	ITEM_CATEGORY_ITEM_CATEGORY_DECORATION        ITEM_CATEGORY = 5
	ITEM_CATEGORY_ITEM_CATEGORY_FOOD              ITEM_CATEGORY = 6
	ITEM_CATEGORY_ITEM_CATEGORY_HELMETS_HATS      ITEM_CATEGORY = 7
	ITEM_CATEGORY_ITEM_CATEGORY_LEGS              ITEM_CATEGORY = 8
	ITEM_CATEGORY_ITEM_CATEGORY_OTHERS            ITEM_CATEGORY = 9
	ITEM_CATEGORY_ITEM_CATEGORY_POTIONS           ITEM_CATEGORY = 10
	ITEM_CATEGORY_ITEM_CATEGORY_RINGS             ITEM_CATEGORY = 11
	ITEM_CATEGORY_ITEM_CATEGORY_RUNES             ITEM_CATEGORY = 12
	ITEM_CATEGORY_ITEM_CATEGORY_SHIELDS           ITEM_CATEGORY = 13
	ITEM_CATEGORY_ITEM_CATEGORY_TOOLS             ITEM_CATEGORY = 14
	ITEM_CATEGORY_ITEM_CATEGORY_VALUABLES         ITEM_CATEGORY = 15
	ITEM_CATEGORY_ITEM_CATEGORY_AMMUNITION        ITEM_CATEGORY = 16
	ITEM_CATEGORY_ITEM_CATEGORY_AXES              ITEM_CATEGORY = 17
	ITEM_CATEGORY_ITEM_CATEGORY_CLUBS             ITEM_CATEGORY = 18
	ITEM_CATEGORY_ITEM_CATEGORY_DISTANCE_WEAPONS  ITEM_CATEGORY = 19
	ITEM_CATEGORY_ITEM_CATEGORY_SWORDS            ITEM_CATEGORY = 20
	ITEM_CATEGORY_ITEM_CATEGORY_WANDS_RODS        ITEM_CATEGORY = 21
	ITEM_CATEGORY_ITEM_CATEGORY_PREMIUM_SCROLLS   ITEM_CATEGORY = 22
	ITEM_CATEGORY_ITEM_CATEGORY_TIBIA_COINS       ITEM_CATEGORY = 23
	ITEM_CATEGORY_ITEM_CATEGORY_CREATURE_PRODUCTS ITEM_CATEGORY = 24
)

// Enum value maps for ITEM_CATEGORY.
var (
	ITEM_CATEGORY_name = map[int32]string{
		1:  "ITEM_CATEGORY_ARMORS",
		2:  "ITEM_CATEGORY_AMULETS",
		3:  "ITEM_CATEGORY_BOOTS",
		4:  "ITEM_CATEGORY_CONTAINERS",
		5:  "ITEM_CATEGORY_DECORATION",
		6:  "ITEM_CATEGORY_FOOD",
		7:  "ITEM_CATEGORY_HELMETS_HATS",
		8:  "ITEM_CATEGORY_LEGS",
		9:  "ITEM_CATEGORY_OTHERS",
		10: "ITEM_CATEGORY_POTIONS",
		11: "ITEM_CATEGORY_RINGS",
		12: "ITEM_CATEGORY_RUNES",
		13: "ITEM_CATEGORY_SHIELDS",
		14: "ITEM_CATEGORY_TOOLS",
		15: "ITEM_CATEGORY_VALUABLES",
		16: "ITEM_CATEGORY_AMMUNITION",
		17: "ITEM_CATEGORY_AXES",
		18: "ITEM_CATEGORY_CLUBS",
		19: "ITEM_CATEGORY_DISTANCE_WEAPONS",
		20: "ITEM_CATEGORY_SWORDS",
		21: "ITEM_CATEGORY_WANDS_RODS",
		22: "ITEM_CATEGORY_PREMIUM_SCROLLS",
		23: "ITEM_CATEGORY_TIBIA_COINS",
		24: "ITEM_CATEGORY_CREATURE_PRODUCTS",
	}
	ITEM_CATEGORY_value = map[string]int32{
		"ITEM_CATEGORY_ARMORS":            1,
		"ITEM_CATEGORY_AMULETS":           2,
		"ITEM_CATEGORY_BOOTS":             3,
		"ITEM_CATEGORY_CONTAINERS":        4,
		"ITEM_CATEGORY_DECORATION":        5,
		"ITEM_CATEGORY_FOOD":              6,
		"ITEM_CATEGORY_HELMETS_HATS":      7,
		"ITEM_CATEGORY_LEGS":              8,
		"ITEM_CATEGORY_OTHERS":            9,
		"ITEM_CATEGORY_POTIONS":           10,
		"ITEM_CATEGORY_RINGS":             11,
		"ITEM_CATEGORY_RUNES":             12,
		"ITEM_CATEGORY_SHIELDS":           13,
		"ITEM_CATEGORY_TOOLS":             14,
		"ITEM_CATEGORY_VALUABLES":         15,
		"ITEM_CATEGORY_AMMUNITION":        16,
		"ITEM_CATEGORY_AXES":              17,
		"ITEM_CATEGORY_CLUBS":             18,
		"ITEM_CATEGORY_DISTANCE_WEAPONS":  19,
		"ITEM_CATEGORY_SWORDS":            20,
		"ITEM_CATEGORY_WANDS_RODS":        21,
		"ITEM_CATEGORY_PREMIUM_SCROLLS":   22,
		"ITEM_CATEGORY_TIBIA_COINS":       23,
		"ITEM_CATEGORY_CREATURE_PRODUCTS": 24,
	}
)

func (x ITEM_CATEGORY) Enum() *ITEM_CATEGORY {
	p := new(ITEM_CATEGORY)
	*p = x
	return p
}

func (x ITEM_CATEGORY) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ITEM_CATEGORY) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[1].Descriptor()
}

func (ITEM_CATEGORY) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[1]
}

func (x ITEM_CATEGORY) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ITEM_CATEGORY) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ITEM_CATEGORY(num)
	return nil
}

// Deprecated: Use ITEM_CATEGORY.Descriptor instead.
func (ITEM_CATEGORY) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{1}
}

type PLAYER_PROFESSION int32

const (
	PLAYER_PROFESSION_PLAYER_PROFESSION_ANY      PLAYER_PROFESSION = -1
	PLAYER_PROFESSION_PLAYER_PROFESSION_NONE     PLAYER_PROFESSION = 0
	PLAYER_PROFESSION_PLAYER_PROFESSION_KNIGHT   PLAYER_PROFESSION = 1
	PLAYER_PROFESSION_PLAYER_PROFESSION_PALADIN  PLAYER_PROFESSION = 2
	PLAYER_PROFESSION_PLAYER_PROFESSION_SORCERER PLAYER_PROFESSION = 3
	PLAYER_PROFESSION_PLAYER_PROFESSION_DRUID    PLAYER_PROFESSION = 4
	PLAYER_PROFESSION_PLAYER_PROFESSION_PROMOTED PLAYER_PROFESSION = 10
)

// Enum value maps for PLAYER_PROFESSION.
var (
	PLAYER_PROFESSION_name = map[int32]string{
		-1: "PLAYER_PROFESSION_ANY",
		0:  "PLAYER_PROFESSION_NONE",
		1:  "PLAYER_PROFESSION_KNIGHT",
		2:  "PLAYER_PROFESSION_PALADIN",
		3:  "PLAYER_PROFESSION_SORCERER",
		4:  "PLAYER_PROFESSION_DRUID",
		10: "PLAYER_PROFESSION_PROMOTED",
	}
	PLAYER_PROFESSION_value = map[string]int32{
		"PLAYER_PROFESSION_ANY":      -1,
		"PLAYER_PROFESSION_NONE":     0,
		"PLAYER_PROFESSION_KNIGHT":   1,
		"PLAYER_PROFESSION_PALADIN":  2,
		"PLAYER_PROFESSION_SORCERER": 3,
		"PLAYER_PROFESSION_DRUID":    4,
		"PLAYER_PROFESSION_PROMOTED": 10,
	}
)

func (x PLAYER_PROFESSION) Enum() *PLAYER_PROFESSION {
	p := new(PLAYER_PROFESSION)
	*p = x
	return p
}

func (x PLAYER_PROFESSION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLAYER_PROFESSION) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[2].Descriptor()
}

func (PLAYER_PROFESSION) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[2]
}

func (x PLAYER_PROFESSION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PLAYER_PROFESSION) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PLAYER_PROFESSION(num)
	return nil
}

// Deprecated: Use PLAYER_PROFESSION.Descriptor instead.
func (PLAYER_PROFESSION) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{2}
}

type ANIMATION_LOOP_TYPE int32

const (
	ANIMATION_LOOP_TYPE_ANIMATION_LOOP_TYPE_PINGPONG ANIMATION_LOOP_TYPE = -1
	ANIMATION_LOOP_TYPE_ANIMATION_LOOP_TYPE_INFINITE ANIMATION_LOOP_TYPE = 0
	ANIMATION_LOOP_TYPE_ANIMATION_LOOP_TYPE_COUNTED  ANIMATION_LOOP_TYPE = 1
)

// Enum value maps for ANIMATION_LOOP_TYPE.
var (
	ANIMATION_LOOP_TYPE_name = map[int32]string{
		-1: "ANIMATION_LOOP_TYPE_PINGPONG",
		0:  "ANIMATION_LOOP_TYPE_INFINITE",
		1:  "ANIMATION_LOOP_TYPE_COUNTED",
	}
	ANIMATION_LOOP_TYPE_value = map[string]int32{
		"ANIMATION_LOOP_TYPE_PINGPONG": -1,
		"ANIMATION_LOOP_TYPE_INFINITE": 0,
		"ANIMATION_LOOP_TYPE_COUNTED":  1,
	}
)

func (x ANIMATION_LOOP_TYPE) Enum() *ANIMATION_LOOP_TYPE {
	p := new(ANIMATION_LOOP_TYPE)
	*p = x
	return p
}

func (x ANIMATION_LOOP_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ANIMATION_LOOP_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[3].Descriptor()
}

func (ANIMATION_LOOP_TYPE) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[3]
}

func (x ANIMATION_LOOP_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ANIMATION_LOOP_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ANIMATION_LOOP_TYPE(num)
	return nil
}

// Deprecated: Use ANIMATION_LOOP_TYPE.Descriptor instead.
func (ANIMATION_LOOP_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{3}
}

type HOOK_TYPE int32

const (
	HOOK_TYPE_HOOK_TYPE_SOUTH HOOK_TYPE = 1
	HOOK_TYPE_HOOK_TYPE_EAST  HOOK_TYPE = 2
)

// Enum value maps for HOOK_TYPE.
var (
	HOOK_TYPE_name = map[int32]string{
		1: "HOOK_TYPE_SOUTH",
		2: "HOOK_TYPE_EAST",
	}
	HOOK_TYPE_value = map[string]int32{
		"HOOK_TYPE_SOUTH": 1,
		"HOOK_TYPE_EAST":  2,
	}
)

func (x HOOK_TYPE) Enum() *HOOK_TYPE {
	p := new(HOOK_TYPE)
	*p = x
	return p
}

func (x HOOK_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HOOK_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_enumTypes[4].Descriptor()
}

func (HOOK_TYPE) Type() protoreflect.EnumType {
	return &file_shared_proto_enumTypes[4]
}

func (x HOOK_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HOOK_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HOOK_TYPE(num)
	return nil
}

// Deprecated: Use HOOK_TYPE.Descriptor instead.
func (HOOK_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{4}
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *uint32                `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y             *uint32                `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z             *uint32                `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_shared_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetX() uint32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Coordinate) GetY() uint32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Coordinate) GetZ() uint32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

var File_shared_proto protoreflect.FileDescriptor

const file_shared_proto_rawDesc = "" +
	"\n" +
	"\fshared.proto\x12\x15tibia.protobuf.shared\"6\n" +
	"\n" +
	"Coordinate\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\rR\x01z*\x94\x01\n" +
	"\rPLAYER_ACTION\x12\x16\n" +
	"\x12PLAYER_ACTION_NONE\x10\x00\x12\x16\n" +
	"\x12PLAYER_ACTION_LOOK\x10\x01\x12\x15\n" +
	"\x11PLAYER_ACTION_USE\x10\x02\x12\x16\n" +
	"\x12PLAYER_ACTION_OPEN\x10\x03\x12$\n" +
	" PLAYER_ACTION_AUTOWALK_HIGHLIGHT\x10\x04*\xb3\x05\n" +
	"\rITEM_CATEGORY\x12\x18\n" +
	"\x14ITEM_CATEGORY_ARMORS\x10\x01\x12\x19\n" +
	"\x15ITEM_CATEGORY_AMULETS\x10\x02\x12\x17\n" +
	"\x13ITEM_CATEGORY_BOOTS\x10\x03\x12\x1c\n" +
	"\x18ITEM_CATEGORY_CONTAINERS\x10\x04\x12\x1c\n" +
	"\x18ITEM_CATEGORY_DECORATION\x10\x05\x12\x16\n" +
	"\x12ITEM_CATEGORY_FOOD\x10\x06\x12\x1e\n" +
	"\x1aITEM_CATEGORY_HELMETS_HATS\x10\a\x12\x16\n" +
	"\x12ITEM_CATEGORY_LEGS\x10\b\x12\x18\n" +
	"\x14ITEM_CATEGORY_OTHERS\x10\t\x12\x19\n" +
	"\x15ITEM_CATEGORY_POTIONS\x10\n" +
	"\x12\x17\n" +
	"\x13ITEM_CATEGORY_RINGS\x10\v\x12\x17\n" +
	"\x13ITEM_CATEGORY_RUNES\x10\f\x12\x19\n" +
	"\x15ITEM_CATEGORY_SHIELDS\x10\r\x12\x17\n" +
	"\x13ITEM_CATEGORY_TOOLS\x10\x0e\x12\x1b\n" +
	"\x17ITEM_CATEGORY_VALUABLES\x10\x0f\x12\x1c\n" +
	"\x18ITEM_CATEGORY_AMMUNITION\x10\x10\x12\x16\n" +
	"\x12ITEM_CATEGORY_AXES\x10\x11\x12\x17\n" +
	"\x13ITEM_CATEGORY_CLUBS\x10\x12\x12\"\n" +
	"\x1eITEM_CATEGORY_DISTANCE_WEAPONS\x10\x13\x12\x18\n" +
	"\x14ITEM_CATEGORY_SWORDS\x10\x14\x12\x1c\n" +
	"\x18ITEM_CATEGORY_WANDS_RODS\x10\x15\x12!\n" +
	"\x1dITEM_CATEGORY_PREMIUM_SCROLLS\x10\x16\x12\x1d\n" +
	"\x19ITEM_CATEGORY_TIBIA_COINS\x10\x17\x12#\n" +
	"\x1fITEM_CATEGORY_CREATURE_PRODUCTS\x10\x18*\xed\x01\n" +
	"\x11PLAYER_PROFESSION\x12\"\n" +
	"\x15PLAYER_PROFESSION_ANY\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\x16PLAYER_PROFESSION_NONE\x10\x00\x12\x1c\n" +
	"\x18PLAYER_PROFESSION_KNIGHT\x10\x01\x12\x1d\n" +
	"\x19PLAYER_PROFESSION_PALADIN\x10\x02\x12\x1e\n" +
	"\x1aPLAYER_PROFESSION_SORCERER\x10\x03\x12\x1b\n" +
	"\x17PLAYER_PROFESSION_DRUID\x10\x04\x12\x1e\n" +
	"\x1aPLAYER_PROFESSION_PROMOTED\x10\n" +
	"*\x83\x01\n" +
	"\x13ANIMATION_LOOP_TYPE\x12)\n" +
	"\x1cANIMATION_LOOP_TYPE_PINGPONG\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x1cANIMATION_LOOP_TYPE_INFINITE\x10\x00\x12\x1f\n" +
	"\x1bANIMATION_LOOP_TYPE_COUNTED\x10\x01*4\n" +
	"\tHOOK_TYPE\x12\x13\n" +
	"\x0fHOOK_TYPE_SOUTH\x10\x01\x12\x12\n" +
	"\x0eHOOK_TYPE_EAST\x10\x02"

var (
	file_shared_proto_rawDescOnce sync.Once
	file_shared_proto_rawDescData []byte
)

func file_shared_proto_rawDescGZIP() []byte {
	file_shared_proto_rawDescOnce.Do(func() {
		file_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_rawDesc), len(file_shared_proto_rawDesc)))
	})
	return file_shared_proto_rawDescData
}

var file_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_proto_goTypes = []any{
	(PLAYER_ACTION)(0),       // 0: tibia.protobuf.shared.PLAYER_ACTION
	(ITEM_CATEGORY)(0),       // 1: tibia.protobuf.shared.ITEM_CATEGORY
	(PLAYER_PROFESSION)(0),   // 2: tibia.protobuf.shared.PLAYER_PROFESSION
	(ANIMATION_LOOP_TYPE)(0), // 3: tibia.protobuf.shared.ANIMATION_LOOP_TYPE
	(HOOK_TYPE)(0),           // 4: tibia.protobuf.shared.HOOK_TYPE
	(*Coordinate)(nil),       // 5: tibia.protobuf.shared.Coordinate
}
var file_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_init() }
func file_shared_proto_init() {
	if File_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_rawDesc), len(file_shared_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_goTypes,
		DependencyIndexes: file_shared_proto_depIdxs,
		EnumInfos:         file_shared_proto_enumTypes,
		MessageInfos:      file_shared_proto_msgTypes,
	}.Build()
	File_shared_proto = out.File
	file_shared_proto_goTypes = nil
	file_shared_proto_depIdxs = nil
}
